# Site settings
title: Yeon-Ho
description: Yeon-Ho Development
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yeon-Ho
user_description: 여기가 간단한 자기 소개
user_title: Web Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  Yeon-Ho
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
